services:
  operations:
    image: postgres:17
    container_name: operations
    environment:
      POSTGRES_USER: ${OPERATIONS_ROOT_USER}
      POSTGRES_PASSWORD: ${OPERATIONS_ROOT_PASSWORD}
      POSTGRES_DB: ${OPERATIONS_ROOT_DB}
    ports:
      - "${OPERATIONS_PORT_MAPPING:-5432}:5432"
    volumes:
      - operations-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:8.4-rc1-alpine3.22
    container_name: redis
    environment:
      REDIS_APPENDONLY: ${REDIS_APPENDONLY:-yes}
      REDIS_APPENDFSYNC: ${REDIS_APPENDFSYNC:-everysec}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-db-volume:/data
    command: >
      redis-server
      --appendonly ${REDIS_APPENDONLY}
      --appendfsync ${REDIS_APPENDFSYNC}
      --requirepass ${REDIS_PASSWORD}

  database-schema:
    image: drawdb
    container_name: database-schema
    ports:
      - "4000:80"
    volumes:
      - .:/app

  platform:
    build:
      context: ${PLATFORM_PATH}
      dockerfile: Dockerfile
    container_name: platform
    volumes:
      - ${PLATFORM_PATH}:/app
    ports:
      - "8000:8000"
    env_file:
      - .dev.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  operations-db-volume:
  redis-db-volume:
